### ISSUE TITLE
378 error?

### ISSUE THREAD

**Issue by DankMemeGuy** [HuggableSquare/vsco-dl#16]
```
Loading initial dataC:/Ruby26/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:736:in `open'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:35:in `open'
        from K:/vsco-dl.rb:60:in `download'
        from K:/vsco-dl.rb:137:in `<main>'

```

**Comment by HuggableSquare** [comment]
The user you're trying to download doesn't exist. The error message isn't very good, but someone else reported that in #13 so I'm going to close this in favor of that.
