### ISSUE TITLE
404 Not Found (OpenURI::HTTPError)

### ISSUE THREAD

**Issue by ghost** [HuggableSquare/vsco-dl#4]
I'm unable to scrape any accounts, and I'm getting the following error:

```
# ruby vsco-dl.rb -o /vsco/ --no-overwrite https://vsco.co/mel_g/images/1
Loading initial data/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from vsco-dl.rb:41:in `<main>'
```

**Comment by HuggableSquare** [comment]
You actually need to pass in just the username instead of the entire URL, e.g. in your example it would be `ruby vsco-dl.rb -o /vsco/ --no-overwrite mel_g`. Hope that helps!

**Comment by ghost** [comment]
Ah my mistake! Thank you
